name: reboot_launcher
description: Graphical User Interface for Project Reboot
version: "10.0.8"

publish_to: 'none'

environment:
  # 3.19.0 is the last version that supports Windows 7/8/8.1 officially
  # I have no clue who is still using Windows 7, but some users requested support, so might as well add it
  # Repository Issue: https://github.com/Auties00/Reboot-Launcher/issues/58
  # Flutter issue: https://github.com/flutter/flutter/issues/140830#issuecomment-1936397549
  sdk: ">=3.0.0 <=3.19.0"

dependencies:
  # The flutter SDK
  flutter:
    sdk: flutter

  # Reboot common module
  reboot_common:
    path: ./../common

  # Windows UI 3
  fluent_ui: ^4.9.1
  flutter_acrylic: ^1.1.4
  fluentui_system_icons: ^1.1.258
  system_theme: ^3.1.1
  skeletons:
    git:
      url: https://github.com/talok/skeletons
      ref: main

  # Window management
  window_manager: ^0.4.2

  # Cryptographic functions
  bcrypt: ^1.1.3
  pointycastle: ^3.9.1

  # Async helpers
  async: ^2.11.0
  sync: ^0.3.0
  synchronized: ^3.3.0+3

  # State management
  get: ^4.6.6

  # Native utilities
  archive: ^3.6.1
  watcher: ^1.1.1
  clipboard: ^0.1.3
  app_links: ^6.3.2
  windows_taskbar: ^1.1.2
  file_picker: ^8.1.2
  url_launcher: ^6.3.0
  local_notifier: ^0.1.6

  # Server browser
  supabase_flutter: ^2.7.0
  dart_ipify: ^1.1.1

  # Storage
  get_storage: ^2.1.1
  path: ^1.9.0

  # Translations
  intl: any
  flutter_localized_locales: ^2.0.5

  # Auto updater
  yaml: ^3.1.2
  package_info_plus: ^8.0.2
  version: ^3.0.2

  # Validate profile
  email_validator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/backend/
    - assets/backend/CloudStorage/
    - assets/backend/Config/
    - assets/backend/profiles/
    - assets/backend/public/
    - assets/backend/responses/
    - assets/backend/responses/Athena/
    - assets/backend/responses/Athena/BattlePass/
    - assets/backend/responses/Athena/Discovery/
    - assets/backend/responses/Campaign/
    - assets/backend/responses/CloudDir/
    - assets/build/