name: reboot_launcher
description: Graphical User Interface for Project Reboot
version: "9.2.7"

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <=4.0.0"

dependencies:
  # The flutter SDK
  flutter:
    sdk: flutter

  # Reboot common module
  reboot_common:
    path: ./../common

  # Windows UI 3
  fluent_ui: ^4.8.7
  flutter_acrylic:
    path: ./dependencies/flutter_acrylic
  fluentui_system_icons: ^1.1.238
  system_theme: ^2.0.0
  skeletons:
    git:
      url: https://github.com/talok/skeletons
      ref: main

  # Window management
  bitsdojo_window: ^0.1.5
  window_manager: ^0.3.8

  # Extract zip archives (for example the reboot.zip)
  archive: ^3.3.1

  # Cryptographic functions
  crypto: ^3.0.2
  bcrypt: ^1.1.3
  pointycastle: ^3.7.3

  # Async helpers
  async: ^2.8.2
  sync: ^0.3.0

  # State management
  get: ^4.6.5

  # Native utilities
  clipboard: ^0.1.3
  app_links: ^6.0.2
  url_protocol: ^1.0.0
  windows_taskbar: ^1.1.2
  file_picker: ^8.0.3
  url_launcher: ^6.1.5
  local_notifier: ^0.1.6

  # Server browser
  supabase_flutter: ^2.5.2
  uuid: ^3.0.6
  dart_ipify: ^1.1.1

  # Storage
  get_storage: ^2.0.3
  universal_disk_space: ^0.2.3
  path: ^1.8.3

  # Translations
  intl: any
  flutter_localized_locales: ^2.0.5

  # Auto updater
  yaml: ^3.1.2
  package_info_plus: ^8.0.0
  version: ^3.0.2

  # Validate profile
  email_validator: ^3.0.0

dependency_overrides:
  xml: ^6.3.0
  http: ^0.13.5
  win32: ^3.0.0
  ffi: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/backend/
    - assets/backend/CloudStorage/
    - assets/backend/Config/
    - assets/backend/profiles/
    - assets/backend/public/
    - assets/backend/responses/
    - assets/backend/responses/Athena/
    - assets/backend/responses/Athena/BattlePass/
    - assets/backend/responses/Athena/Discovery/
    - assets/backend/responses/Campaign/
    - assets/backend/responses/CloudDir/
    - assets/build/