name: reboot_common
version: "1.0.0"

publish_to: 'none'

environment:
  sdk: ">=2.19.0 <=3.3.3"

dependencies:
  win32: 3.0.0
  ffi: ^2.1.0
  path: ^1.8.3
  http: ^1.1.0
  crypto: ^3.0.2
  archive: ^3.3.7
  ini: ^2.1.0
  shelf_proxy: ^1.0.2
  sync: ^0.3.0

dev_dependencies:
  flutter_lints: ^2.0.1